### ISSUE TITLE
Cookie manager triggers a rerun

### ISSUE THREAD

**Issue by benlindsay** [Mohamed-512/Extra-Streamlit-Components#58]
I've noticed that creating the cookie manager triggers a rerun of the streamlit app, which makes it difficult to work with.

For example, with this app:

```python
import extra_streamlit_components as stx
import streamlit as st


cookie_manager = stx.CookieManager()
st.session_state["run_count"] = st.session_state.get("run_count", 0) + 1
st.write("run_count:", st.session_state["run_count"])
```

It will flash "run_count: 1" faster than the eye can see and then land immediately on "run_count: 2".

Now, if we add `time.sleep(2)` after the CookieManager() call:

```python
import extra_streamlit_components as stx
import streamlit as st
import time


cookie_manager = stx.CookieManager()
time.sleep(2)
st.session_state["run_count"] = st.session_state.get("run_count", 0) + 1
st.write("run_count:", st.session_state["run_count"])
```

The rerun happens during the sleep, before the increment happens, and we land on "run_count: 1".

This rerun complicates things like buttons, since the rerun reverts the buttons state back to False. For example, with this app:

```python
import extra_streamlit_components as stx
import streamlit as st
import time


if st.button("Button"):
    st.session_state["button_clicked"] = True
    cookie_manager = stx.CookieManager()
    time.sleep(2)
    st.write("Button clicked")
st.session_state["run_count"] = st.session_state.get("run_count", 0) + 1
st.write("run_count:", st.session_state["run_count"])
```

We will never see the "Button clicked" message, because the rerun is triggered by CookieManager() which takes place during the sleep, and when the rerun occurs, `st.button("Button")` is now `False`. To get the button click to trigger actions that occur after the CookieManager() call, we need to use session state like this (or something similar):

```python
import extra_streamlit_components as stx
import streamlit as st
import time


if st.session_state.get("button_clicked", False):
    st.write("In session state if statement")
    st.session_state["button_clicked"] = False
if st.button("Button"):
    st.session_state["button_clicked"] = True
    cookie_manager = stx.CookieManager()
    time.sleep(2)
    st.write("In button if statement")
st.session_state["run_count"] = st.session_state.get("run_count", 0) + 1
st.write("run_count:", st.session_state["run_count"])
```

Is this expected behavior? Is there a way to prevent the rerun? Any help would be appreciated.

**Comment by benlindsay** [comment]
Additional discussion here: https://discuss.streamlit.io/t/cookies-support-in-streamlit/16144/35

**Comment by Mohamed-512** [comment]
Should be fixed in 0.1.70

**Comment by informatica92** [comment]
I am currently using the 0.1.71 but it seems that the rerun triggered by calling stx.CookieManager() is still present.

Anyone else with the same issue?

**Comment by lionelta** [comment]
This seems to be working quite well for me.  

``` python
#!/usr/intel/pkgs/python3/3.11.1/bin/python3
import streamlit as st
import extra_streamlit_components as stx
import time

def loading(text):
    with st.spinner(text):
        time.sleep(2)

def get_manager():
    cm = stx.CookieManager()
    loading(f"Loading cookies {st.session_state.count} ...")
    return cm

if 'count' not in st.session_state:
    st.session_state.count = 0

if not st.session_state.count:
    st.session_state.cm = get_manager()

st.session_state.count += 1


if 'userid' in st.session_state.cm.cookies:
    st.write(f"Welcome back {st.session_state.cm.cookies['userid']}!")
    if st.button("Logout"):
        st.session_state.cm.delete('userid')
        loading("Logging out...")
else:
    userid = st.text_input("Enter your user id")
    if userid:
        st.session_state.cm.set('userid', userid)
        loading("Logging in...")


st.info(f"Session count: {st.session_state.count}")
st.write(st.session_state.cm.cookies)
st.write(st.session_state)

```

streamlit==1.41.1
extra_streamlit-components==0.1.71
